-- Drop các bảng dùng CASCADE CONSTRAINTS

DROP TABLE TOKEN_STATUS CASCADE CONSTRAINTS;
DROP TABLE TOKEN CASCADE CONSTRAINTS;
DROP TABLE ATTENDANCE CASCADE CONSTRAINTS;
DROP TABLE POINT_UPDATE_HISTORY CASCADE CONSTRAINTS;
DROP TABLE PACKAGE_DETAIL CASCADE CONSTRAINTS;
DROP TABLE INVOICE_DETAIL CASCADE CONSTRAINTS;
DROP TABLE ORDER_DETAIL CASCADE CONSTRAINTS;
DROP TABLE CANCELLATION CASCADE CONSTRAINTS;
DROP TABLE STORE_INVENTORY CASCADE CONSTRAINTS;
DROP TABLE SHIFT_CLOSING_REPORT CASCADE CONSTRAINTS;
DROP TABLE PACKAGE CASCADE CONSTRAINTS;
DROP TABLE INVOICE CASCADE CONSTRAINTS;
DROP TABLE "ORDER" CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE PROMOTION CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE STORE CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE SUPPLIER CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE PACKAGE_STATUS CASCADE CONSTRAINTS;
DROP TABLE INVOICE_STATUS CASCADE CONSTRAINTS;
DROP TABLE PAYMENT_METHOD CASCADE CONSTRAINTS;
DROP TABLE ROLE CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE_STATUS CASCADE CONSTRAINTS;

PURGE recyclebin;

