-- THIS FILE IS FINALIZED AND SEALED.
-- DO NOT MODIFY THIS FILE.
-- [SEALED BY HELIOS 23/5/2025] --

BEGIN
    -- 1) DELETE OLD JOBS (IF EXISTS)
    BEGIN
        DBMS_SCHEDULER.DROP_JOB(
                JOB_NAME => 'CSMS_ADMIN.JOB_RESET_ALL_SEQS',
                FORCE => TRUE
        );
    EXCEPTION
        WHEN OTHERS THEN
            -- ORA-27475: JOB DOES NOT EXIST
            IF SQLCODE != -27475 THEN
                RAISE;
            END IF;
    END;

    -- 2) CREATE NEW JOB
    DBMS_SCHEDULER.CREATE_JOB(
            JOB_NAME => 'CSMS_ADMIN.JOB_RESET_ALL_SEQS',
            JOB_TYPE => 'PLSQL_BLOCK',
            JOB_ACTION =>
                'BEGIN
                   DECLARE
                     CURSOR SEQS IS
                       SELECT SEQUENCE_NAME
                         FROM USER_SEQUENCES
                        WHERE SEQUENCE_NAME IN (
                          ''ACC_SEQ'',''ASG_SEQ'',''CAT_SEQ'',''EMP_SEQ'',
                          ''INV_SEQ'',''MEMBER_SEQ'',''PAYCHECK_SEQ'',''PAYMENT_SEQ'',
                          ''POINT_SEQ'',''PROMO_SEQ'',''ROLE_SEQ'',''SHIFT_SEQ'',
                          ''STORE_SEQ'',''TOKEN_SEQ'',''INVENTORY_SEQ'',''INVENTORY_TRANSACTION_SEQ'',
                        );
                   BEGIN
                     FOR R IN SEQS LOOP
                       EXECUTE IMMEDIATE ''DROP SEQUENCE '' || R.SEQUENCE_NAME;
                     END LOOP;

                     -- RECREATE SEQUENCES
                     EXECUTE IMMEDIATE ''CREATE SEQUENCE ACC_SEQ                   START WITH 1 INCREMENT BY 1 MAXVALUE 999999   CYCLE   NOCACHE'';
                     EXECUTE IMMEDIATE ''CREATE SEQUENCE ASG_SEQ                   START WITH 1 INCREMENT BY 1 MAXVALUE 9999     CYCLE   NOCACHE'';
                     EXECUTE IMMEDIATE ''CREATE SEQUENCE CAT_SEQ                   START WITH 1 INCREMENT BY 1 MAXVALUE 99999    CYCLE   NOCACHE'';
                     EXECUTE IMMEDIATE ''CREATE SEQUENCE EMP_SEQ                   START WITH 1 INCREMENT BY 1 MAXVALUE 999999   CYCLE   NOCACHE'';
                     EXECUTE IMMEDIATE ''CREATE SEQUENCE INV_SEQ                   START WITH 1 INCREMENT BY 1 MAXVALUE 999999   CYCLE   NOCACHE'';
                     EXECUTE IMMEDIATE ''CREATE SEQUENCE MEMBER_SEQ                START WITH 1 INCREMENT BY 1 MAXVALUE 9999     CYCLE   NOCACHE'';
                     EXECUTE IMMEDIATE ''CREATE SEQUENCE PAYCHECK_SEQ              START WITH 1 INCREMENT BY 1 MAXVALUE 999999   CYCLE   NOCACHE'';
                     EXECUTE IMMEDIATE ''CREATE SEQUENCE PAYMENT_SEQ               START WITH 1 INCREMENT BY 1 MAXVALUE 999      NOCYCLE NOCACHE'';
                     EXECUTE IMMEDIATE ''CREATE SEQUENCE POINT_SEQ                 START WITH 1 INCREMENT BY 1 MAXVALUE 9999     CYCLE   NOCACHE'';
                     EXECUTE IMMEDIATE ''CREATE SEQUENCE PROMO_SEQ                 START WITH 1 INCREMENT BY 1 MAXVALUE 999999   NOCYCLE NOCACHE'';
                     EXECUTE IMMEDIATE ''CREATE SEQUENCE ROLE_SEQ                  START WITH 1 INCREMENT BY 1 MAXVALUE 999      NOCYCLE NOCACHE'';
                     EXECUTE IMMEDIATE ''CREATE SEQUENCE SHIFT_SEQ                 START WITH 1 INCREMENT BY 1 MAXVALUE 9999     CYCLE   NOCACHE'';
                     EXECUTE IMMEDIATE ''CREATE SEQUENCE STORE_SEQ                 START WITH 1 INCREMENT BY 1 MAXVALUE 999999   NOCYCLE NOCACHE'';
                     EXECUTE IMMEDIATE ''CREATE SEQUENCE TOKEN_SEQ                 START WITH 1 INCREMENT BY 1 MAXVALUE 99999999 CYCLE   NOCACHE'';
                     EXECUTE IMMEDIATE ''CREATE SEQUENCE INVENTORY_TRANSACTION_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 99999999 CYCLE   NOCACHE'';
                     EXECUTE IMMEDIATE ''CREATE SEQUENCE INVENTORY_SEQ             START WITH 1 INCREMENT BY 1 MAXVALUE 999999   CYCLE   NOCACHE'';
                   END;
                 END;',
            START_DATE => CAST(TRUNC(SYSDATE + 1) AS TIMESTAMP),
            REPEAT_INTERVAL => 'FREQ=DAILY; BYHOUR=0; BYMINUTE=0; BYSECOND=0',
            ENABLED => TRUE,
            AUTO_DROP => FALSE,
            COMMENTS => 'RESET TẤT CẢ SEQUENCE VỀ GIÁ TRỊ KHỞI ĐẦU MỖI ĐÊM'
    );
END;
/