BEGIN
    -- 1. Xoá job cũ (nếu có)
    BEGIN
        DBMS_SCHEDULER.DROP_JOB(
                job_name => 'CSMS_ADMIN.JOB_RESET_ALL_SEQS',
                force => TRUE
        );
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -27475 THEN -- ORA-27475: job does not exist
                RAISE;
            END IF;
    END;

    -- 2. Tạo job mới
    DBMS_SCHEDULER.CREATE_JOB(
            job_name => 'CSMS_ADMIN.JOB_RESET_ALL_SEQS',
            job_type => 'PLSQL_BLOCK',
            job_action => q'[
      BEGIN
        -- DROP tất cả sequence
        FOR seq_name IN (
          SELECT object_name
          FROM user_objects
          WHERE object_type = 'SEQUENCE'
            AND object_name IN (
              'ACC_SEQ', 'ASG_SEQ', 'CAT_SEQ','EMP_SEQ','INV_SEQ', 'MEMBER_SEQ', 'PAYCHECK_SEQ',
              'POINT_SEQ', 'PAY_SEQ','PROMO_SEQ','ROLE_SEQ','SHIFT_SEQ',
              'STORE_SEQ', 'TOKEN_SEQ'
            )
        ) LOOP
          EXECUTE IMMEDIATE 'DROP SEQUENCE ' || seq_name.object_name;
        END LOOP;

        -- RECREATE mỗi sequence với START và INCREMENT như ban đầu
        EXECUTE IMMEDIATE 'CREATE SEQUENCE ACC_SEQ   START WITH 000001 INCREMENT BY 1 NOCACHE';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE ASG_SEQ   START WITH 0001 INCREMENT BY 1 NOCACHE';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE CAT_SEQ   START WITH 00001  INCREMENT BY 1 NOCACHE';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE EMP_SEQ   START WITH 000001 INCREMENT BY 1 NOCACHE';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE INV_SEQ   START WITH 0001   INCREMENT BY 1 NOCACHE';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE MEMBER_SEQ   START WITH 0001   INCREMENT BY 1 NOCACHE';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE PAYCHECK_SEQ START WITH 000001 INCREMENT BY 1 NOCACHE';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE POINT_SEQ START WITH 000001 MAXVALUE 999999 CYCLE INCREMENT BY 1 NOCACHE';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE PAY_SEQ   START WITH 001    INCREMENT BY 1 NOCACHE';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE PROMO_SEQ START WITH 000001 INCREMENT BY 1 NOCACHE';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE ROLE_SEQ  START WITH 001    INCREMENT BY 1 NOCACHE';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE SHIFT_SEQ START WITH 01     INCREMENT BY 1 NOCACHE';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE STORE_SEQ START WITH 000001 INCREMENT BY 1 NOCACHE';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE TOKEN_SEQ START WITH 00000001 INCREMENT BY 1 NOCACHE';
      END;
    ]',
            start_date => TRUNC(SYSDATE + 1), -- lần chạy đầu là 00:00 hôm sau
            repeat_interval => 'FREQ=DAILY; BYHOUR=0; BYMINUTE=0; BYSECOND=0',
            enabled => TRUE,
            comments => 'Job reset tất cả sequence về giá trị khởi đầu mỗi đêm'
    );
END;
/
